# Introduction to usage of 'heart' package via examples

```{r, eval=FALSE}
library(heart)
data(simuDat)
simuFit <- heart(formula = survrec::Survr(ID, time, event) ~ X1 + group, 
                  data = simuDat, baselinepieces = seq(28, 168, length = 6))
show(simuFit) 
summary(simuFit)
coef(simuFit)
confint(simuFit)
baseline(simuFit)
# Empirical MCF
eMCF <- MCF(survrec::Survr(ID, time, event) ~ group, data = simuDat)
plotMCF(eMCF)
# Estimated MCF from HEART model
# baseline
hMCF1 <- MCF(simuFit)
plotMCF(hMCF1, conf.int = TRUE)

newdata <- rbind(head(simuDat, 1), tail(simuDat, 1))
hMCF2 <- MCF(simuFit, newdata = newdata, 
             groupname = "patgroup", grouplevels = levels(simuDat$group))

plotMCF(hMCF2, conf.int = TRUE)

```

```{r simulation_1, eval=FALSE}
# ## simulation study #1
# ## 200 patients with follow-up period: 24 * 7 = 168 days.
# ## covariate: treatment group, factor with level: treatment and control
# ## fit 6 baselinepieces heart model due to 6 visits
# beta <- 0.3
# theta <- 0.5
# alpha <- 0.06
# 
# ## generate event times for each process 
# ## which depends on random seed by myseed and covariate by x
simu1_fun <- function(beta = 0.3, theta = 0.5, alpha = 0.06, 
                      baselinepieces = 168, x = 0, myseed = 1216, tau = 168) {
  ## generate rate functions for a single process
  set.seed(myseed)
  r <- rgamma(n = 1, shape = theta, scale = 1/theta)
  rho <- r * alpha * exp(crossprod(beta, x))
  ## step 1: calculate the supremum value of rate function for each process
  rho_m <- max(rho)
  ## step 2: simulate W_i every time
  set.seed(myseed)
  W <- NULL
  timeinter <- NULL
  while (is.null(W) || sum(W) <= tau) {
  W <- c(W, rexp(n = 1, rate = rho_m))
  ## step 3
  timeinter <- c(timeinter, sum(W))
  }
  timeinter <- head(timeinter, length(timeinter) - 1)
  timeinter <- round(timeinter, digits = 0)
  ## step 4
  set.seed(myseed)
  tempn <- length(timeinter)
  U <- runif(n = tempn, min = 0, max = 1)
  rho_t <- apply(as.array(timeinter), 1, 
                 whereT, baselinepieces = baselinepieces)
  ind <- U <= rho_t / rho_m
  timeout <- c(timeinter[ind], tau)
  eventout <- c(rep(1, length(timeout) - 1), 0)
  res <- data.frame(ID = myseed, time = timeout, event = eventout, t(x))
  return(res)
}
## generate data for simulation study No.1
simu1_dat <- NULL
for (i in 1:200) {
  simu1_dat <- rbind(simu1_dat, 
                     simu1_fun(myseed = i, x = ifelse(i <= 100, 0, 1)))
}

simu1 <- heart(formula = survrec::Survr(ID, time, event) ~ x, 
               data = simu1_dat, baselinepieces = seq(28, 168, length = 5))
show(simu1) 
summary(simu1)
coef(simu1)
confint(simu1)
baseline(simu1)
plot.baseline(simu1)

## generate simulation data to export as example data 
simuDat <- NULL
set.seed(1216)
for (i in 1:200) {
  simuDat <- rbind(simuDat, 
                    simu1_fun(myseed = i,
                              beta = c(0.3, 1.5),
                              x = rbind(ifelse(i <= 100, 0, 1), rnorm(1))))
}
simuDat$X2 <- round(simuDat$X2, digits = 2)
simuDat$X1 <- factor(simuDat$X1, levels = c(0, 1), labels = c("Treat", "Contr"))
colnames(simuDat)[4:5] <- c("group", "X1")
save(simuDat, file = "data/simuDat.RData")


## dataset: colon from package survrec
# require(survrec)
# data(colon)
# testdat <- colon
# BaselinePieces <- quantile(testdat$time, probs = c(0.25, 0.5, 0.75, 1))
# attr(BaselinePieces, "names") <- NULL
# BaselinePieces
# [1]  21  216  880 2175
```
