---
title: "Introduction to 'reda' via examples"
author: Wenjie Wang
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Introduction to 'heart' via examples}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---

# The HEART Model

## Model Fitting

```{r fits, message=FALSE}
library(reda)
heartFit <- heart(formula = Survr(ID, time, event) ~ x1 + group, 
                  data = simuDat, baselinePieces = seq(28, 168, length = 6))
```

## Estimates 

```{r estimates}
# point estimates of coefficients
coef(heartFit)
# confidence interval for coefficients
confint(heartFit)
# estimates of piece-wise constant baseline rate function
baseline(heartFit)
```

## Summary of the Model Fits

```{r summary}
# a brief summary for the model fits
heartFit 
# summary in more details
summary(heartFit)
```

# Mean Cumulative Function (MCF)

## Empirical MCF

```{r empirMcf}
mcf(Survr(ID, time, event) ~ group, data = simuDat,
    subset = ID %in% 100:101, na.action = na.omit, level = 0.9)
sampleMCF <- mcf(Survr(ID, time, event) ~ group, data = simuDat)
```

```{r plotempir, fig.height=6, fig.width=7}
plotMcf(sampleMCF, conf.int = TRUE, mark.time = TRUE, 
        lty = c(1, 3), col = c("orange", "navy"))
```

## Estimated MCF from the HEART Model

Note that function 'plotMcf' returns 'ggplot' object so that the plot can be 
further customized properly.

### Baseline MCF 

```{r baselineMCF, fig.height=6, fig.width=7}
baselineMcf <- mcf(heartFit)
plotMcf(baselineMcf, conf.int = TRUE, col = "royalblue") +
    ggplot2::theme_bw()
```

### MCF for certain group(s)

```{r heartMcf, fig.height=6, fig.width=7}
estmcf <- mcf(heartFit, 
              newdata = data.frame(
                  x1 = c(0.1, 0.1), 
                  group = gl(2, 1, labels = c("Treat", "Contr"))), 
              groupName = "Group", 
              groupLevels = c("Treatment", "Control"))
plotMcf(estmcf, conf.int = TRUE, col = c("royalblue", "red")) +
    ggplot2::theme_bw()
```
