##
## R package reda by Wenjie Wang, Haoda Fu, and Jun Yan
## Copyright (C) 2015-2020
##
## This file is part of the R package reda.
##
## The R package reda is free software: You can redistribute it and/or
## modify it under the terms of the GNU General Public License as published by
## the Free Software Foundation, either version 3 of the License, or any later
## version (at your option). See the GNU General Public License at
## <https://www.gnu.org/licenses/> for details.
##
## The R package reda is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
##

# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_np_mcf <- function(time1, time2, id, event, point_method = 1L, var_method = 1L, ci_method = 1L, ci_level = 0.95, var_bootstrap_method = 1L, var_bootstrap_B = 30L) {
    .Call('_reda_cpp_np_mcf', PACKAGE = 'reda', time1, time2, id, event, point_method, var_method, ci_method, ci_level, var_bootstrap_method, var_bootstrap_B)
}

rrisk_exponential <- function(z, zCoef) {
    .Call('_reda_rrisk_exponential', PACKAGE = 'reda', z, zCoef)
}

rrisk_linear <- function(z, zCoef) {
    .Call('_reda_rrisk_linear', PACKAGE = 'reda', z, zCoef)
}

rrisk_excess <- function(z, zCoef) {
    .Call('_reda_rrisk_excess', PACKAGE = 'reda', z, zCoef)
}

