# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_np_mcf <- function(time1, time2, id, event, point_method = 1L, var_method = 1L, ci_method = 1L, ci_level = 0.95, var_bootstrap_method = 1L, var_bootstrap_B = 30L) {
    .Call('_reda_cpp_np_mcf', PACKAGE = 'reda', time1, time2, id, event, point_method, var_method, ci_method, ci_level, var_bootstrap_method, var_bootstrap_B)
}

rrisk_exponential <- function(z, zCoef) {
    .Call('_reda_rrisk_exponential', PACKAGE = 'reda', z, zCoef)
}

rrisk_linear <- function(z, zCoef) {
    .Call('_reda_rrisk_linear', PACKAGE = 'reda', z, zCoef)
}

rrisk_excess <- function(z, zCoef) {
    .Call('_reda_rrisk_excess', PACKAGE = 'reda', z, zCoef)
}

rcpp_factorize <- function(x) {
    .Call('_reda_rcpp_factorize', PACKAGE = 'reda', x)
}

