# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rrisk_exponential <- function(z, zCoef) {
    .Call('_reda_rrisk_exponential', PACKAGE = 'reda', z, zCoef)
}

rrisk_linear <- function(z, zCoef) {
    .Call('_reda_rrisk_linear', PACKAGE = 'reda', z, zCoef)
}

rrisk_excess <- function(z, zCoef) {
    .Call('_reda_rrisk_excess', PACKAGE = 'reda', z, zCoef)
}

